using KrishiSahayAI.Models;
using System.Data.Common;
using Microsoft.Data.Sqlite;
using Npgsql;

namespace KrishiSahayAI.Data
{
    public class AppDb
    {
        private readonly string _connectionString;
        private readonly bool _usePostgres;

        public AppDb(IConfiguration configuration)
        {
            var cloudSqlSocket =
                Environment.GetEnvironmentVariable("INSTANCE_UNIX_SOCKET");

            _usePostgres =
                !string.IsNullOrWhiteSpace(cloudSqlSocket);

            if (_usePostgres)
            {
                var dbUser =
                    Environment.GetEnvironmentVariable("DB_USER");

                var dbPassword =
                    Environment.GetEnvironmentVariable("DB_PASS");

                var dbName =
                    Environment.GetEnvironmentVariable("DB_NAME");

                if (string.IsNullOrWhiteSpace(dbUser) ||
                    string.IsNullOrWhiteSpace(dbPassword) ||
                    string.IsNullOrWhiteSpace(dbName))
                {
                    throw new InvalidOperationException(
                        "Cloud SQL environment variables DB_USER, DB_PASS and DB_NAME are required.");
                }

                _connectionString =
                    $"Host={cloudSqlSocket};" +
                    $"Username={dbUser};" +
                    $"Password={dbPassword};" +
                    $"Database={dbName};" +
                    "Ssl Mode=Disable;" +
                    "Pooling=true;";
            }
            else
            {
                var databasePath =
                    configuration["Database:Path"]
                    ?? "Data/krishisahay.db";

                var directory =
                    Path.GetDirectoryName(databasePath);

                if (!string.IsNullOrWhiteSpace(directory))
                {
                    Directory.CreateDirectory(directory);
                }

                _connectionString =
                    $"Data Source={databasePath}";
            }
        }

        private DbConnection CreateConnection()
        {
            if (_usePostgres)
            {
                return new NpgsqlConnection(_connectionString);
            }

            return new SqliteConnection(_connectionString);
        }

        private static void AddParameter(
            DbCommand command,
            string name,
            object? value)
        {
            var parameter = command.CreateParameter();
            parameter.ParameterName = name;
            parameter.Value = value ?? DBNull.Value;
            command.Parameters.Add(parameter);
        }


        // =========================================================
        // DATABASE INITIALIZATION
        // =========================================================

        public void Initialize()
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText =
                _usePostgres
                    ? @"
CREATE TABLE IF NOT EXISTS FarmProfiles
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId TEXT NOT NULL,
    FarmerName TEXT NOT NULL,
    Location TEXT,
    LandSize DOUBLE PRECISION,
    LandUnit TEXT,
    SoilType TEXT,
    WaterSource TEXT,
    FarmingMethod TEXT,
    Crop TEXT,
    ExperienceLevel TEXT,
    Budget NUMERIC,
    CreatedAt TEXT
);

CREATE TABLE IF NOT EXISTS FarmCrops
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserId TEXT NOT NULL,
    FarmId INTEGER NOT NULL,
    CropName TEXT NOT NULL,
    Variety TEXT,
    Season TEXT,
    Area DOUBLE PRECISION NOT NULL DEFAULT 0,
    AreaUnit TEXT NOT NULL DEFAULT 'Acre',
    SowingDate TEXT,
    Notes TEXT,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY (FarmId) REFERENCES FarmProfiles(Id)
);

CREATE TABLE IF NOT EXISTS FarmActivities
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FarmProfileId INTEGER,
    Title TEXT,
    Description TEXT,
    ActivityDate TEXT,
    IsCompleted INTEGER,
    Category TEXT
);

CREATE TABLE IF NOT EXISTS LearningLessonCompletions
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FarmProfileId INTEGER NOT NULL,
    TopicId INTEGER NOT NULL,
    LessonId INTEGER NOT NULL,
    CompletedAt TEXT NOT NULL,
    UNIQUE (FarmProfileId, TopicId, LessonId)
);

CREATE TABLE IF NOT EXISTS CropObservations
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FarmProfileId INTEGER,
    CropName TEXT,
    ImagePath TEXT,
    Observation TEXT,
    AiResult TEXT,
    CreatedAt TEXT
);

CREATE TABLE IF NOT EXISTS SoilAssessments
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FarmProfileId INTEGER NOT NULL,
    SoilKnowledge TEXT,
    SoilTexture TEXT,
    SoilColour TEXT,
    Drainage TEXT,
    PreviousCrop TEXT,
    SoilTestStatus TEXT,
    Result TEXT,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY (FarmProfileId) REFERENCES FarmProfiles(Id)
);

CREATE TABLE IF NOT EXISTS WaterAssessments
(
    Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FarmProfileId INTEGER NOT NULL,
    WaterSource TEXT,
    WaterAvailability TEXT,
    IrrigationMethod TEXT,
    IrrigationFrequency TEXT,
    WaterQualityKnowledge TEXT,
    DrainageCondition TEXT,
    RecentWaterProblem TEXT,
    Result TEXT,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY (FarmProfileId) REFERENCES FarmProfiles(Id)
);
"
                    : @"
CREATE TABLE IF NOT EXISTS FarmProfiles
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId TEXT NOT NULL,
    FarmerName TEXT NOT NULL,
    Location TEXT,
    LandSize REAL,
    LandUnit TEXT,
    SoilType TEXT,
    WaterSource TEXT,
    FarmingMethod TEXT,
    Crop TEXT,
    ExperienceLevel TEXT,
    Budget REAL,
    CreatedAt TEXT
);

CREATE TABLE IF NOT EXISTS FarmCrops
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId TEXT NOT NULL,
    FarmId INTEGER NOT NULL,
    CropName TEXT NOT NULL,
    Variety TEXT,
    Season TEXT,
    Area REAL NOT NULL DEFAULT 0,
    AreaUnit TEXT NOT NULL DEFAULT 'Acre',
    SowingDate TEXT,
    Notes TEXT,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY (FarmId) REFERENCES FarmProfiles(Id)
);

CREATE TABLE IF NOT EXISTS FarmActivities
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FarmProfileId INTEGER,
    Title TEXT,
    Description TEXT,
    ActivityDate TEXT,
    IsCompleted INTEGER,
    Category TEXT
);

CREATE TABLE IF NOT EXISTS LearningLessonCompletions
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FarmProfileId INTEGER NOT NULL,
    TopicId INTEGER NOT NULL,
    LessonId INTEGER NOT NULL,
    CompletedAt TEXT NOT NULL,
    UNIQUE (FarmProfileId, TopicId, LessonId)
);

CREATE TABLE IF NOT EXISTS CropObservations
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FarmProfileId INTEGER,
    CropName TEXT,
    ImagePath TEXT,
    Observation TEXT,
    AiResult TEXT,
    CreatedAt TEXT
);

CREATE TABLE IF NOT EXISTS SoilAssessments
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FarmProfileId INTEGER NOT NULL,
    SoilKnowledge TEXT,
    SoilTexture TEXT,
    SoilColour TEXT,
    Drainage TEXT,
    PreviousCrop TEXT,
    SoilTestStatus TEXT,
    Result TEXT,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY (FarmProfileId) REFERENCES FarmProfiles(Id)
);

CREATE TABLE IF NOT EXISTS WaterAssessments
(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FarmProfileId INTEGER NOT NULL,
    WaterSource TEXT,
    WaterAvailability TEXT,
    IrrigationMethod TEXT,
    IrrigationFrequency TEXT,
    WaterQualityKnowledge TEXT,
    DrainageCondition TEXT,
    RecentWaterProblem TEXT,
    Result TEXT,
    CreatedAt TEXT NOT NULL,
    FOREIGN KEY (FarmProfileId) REFERENCES FarmProfiles(Id)
);
";

            command.ExecuteNonQuery();

            // Keep the old local test-data correction only for SQLite.
            // Cloud SQL starts with a clean persistent schema.
            if (!_usePostgres)
            {
                using var correctionCommand =
                    connection.CreateCommand();

                correctionCommand.CommandText = @"
UPDATE CropObservations
SET CropName = 'Wheat'
WHERE FarmProfileId = 3
AND CropName = 'Groundnut'
AND Observation = 'leaves turning yellow'
AND AiResult LIKE '%wheat%';
";

                correctionCommand.ExecuteNonQuery();
            }
        }


        // =========================================================
        // FARM PROFILE
        // =========================================================

        public int SaveFarm(FarmProfile farm)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText = @"
INSERT INTO FarmProfiles
(
    UserId,
    FarmerName,
    Location,
    LandSize,
    LandUnit,
    SoilType,
    WaterSource,
    FarmingMethod,
    Crop,
    ExperienceLevel,
    Budget,
    CreatedAt
)
VALUES
(
    @UserId,
    @FarmerName,
    @Location,
    @LandSize,
    @LandUnit,
    @SoilType,
    @WaterSource,
    @FarmingMethod,
    @Crop,
    @ExperienceLevel,
    @Budget,
    @CreatedAt
);

RETURNING Id;
";

            AddParameter(command,
                "@UserId",
                farm.UserId);

            AddParameter(command,
                "@FarmerName",
                farm.FarmerName);

            AddParameter(command,
                "@Location",
                farm.Location);

            AddParameter(command,
                "@LandSize",
                farm.LandSize);

            AddParameter(command,
                "@LandUnit",
                farm.LandUnit);

            AddParameter(command,
                "@SoilType",
                farm.SoilType);

            AddParameter(command,
                "@WaterSource",
                farm.WaterSource);

            AddParameter(command,
                "@FarmingMethod",
                farm.FarmingMethod);

            AddParameter(command,
                "@Crop",
                farm.Crop);

            AddParameter(command,
                "@ExperienceLevel",
                farm.ExperienceLevel);

            AddParameter(command,
                "@Budget",
                farm.Budget);

            AddParameter(command,
                "@CreatedAt",
                farm.CreatedAt.ToString("O"));

            return Convert.ToInt32(
                command.ExecuteScalar());
        }
        public int SaveFarmCrop(FarmCrop crop)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
INSERT INTO FarmCrops
(
    UserId,
    FarmId,
    CropName,
    Variety,
    Season,
    Area,
    AreaUnit,
    SowingDate,
    Notes,
    CreatedAt
)
VALUES
(
    @UserId,
    @FarmId,
    @CropName,
    @Variety,
    @Season,
    @Area,
    @AreaUnit,
    @SowingDate,
    @Notes,
    @CreatedAt
);

RETURNING Id;
";

            AddParameter(command,
                "@UserId",
                crop.UserId);

            AddParameter(command,
                "@FarmId",
                crop.FarmId);

            AddParameter(command,
                "@CropName",
                crop.CropName);

            AddParameter(command,
                "@Variety",
                crop.Variety ?? "");

            AddParameter(command,
                "@Season",
                crop.Season ?? "");

            AddParameter(command,
                "@Area",
                crop.Area);

            AddParameter(command,
                "@AreaUnit",
                crop.AreaUnit ?? "Acre");

            AddParameter(command,
                "@SowingDate",
                crop.SowingDate?.ToString("O")
                ?? (object)DBNull.Value);

            AddParameter(command,
                "@Notes",
                crop.Notes ?? "");

            AddParameter(command,
                "@CreatedAt",
                crop.CreatedAt.ToString("O"));

            return Convert.ToInt32(
                command.ExecuteScalar());
        }

        public List<FarmCrop> GetFarmCrops(
    int farmId,
    string userId)
        {
            var crops = new List<FarmCrop>();

            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmCrops
WHERE FarmId = @FarmId
AND UserId = @UserId
ORDER BY Id DESC;
";

            AddParameter(command,
                "@FarmId",
                farmId);

            AddParameter(command,
                "@UserId",
                userId);

            using var reader =
                command.ExecuteReader();

            while (reader.Read())
            {
                DateTime? sowingDate = null;

                var sowingDateValue =
                    reader["SowingDate"]?.ToString();

                if (!string.IsNullOrWhiteSpace(
                        sowingDateValue))
                {
                    if (DateTime.TryParse(
                            sowingDateValue,
                            out var parsedDate))
                    {
                        sowingDate = parsedDate;
                    }
                }

                crops.Add(new FarmCrop
                {
                    Id = reader.GetInt32(
                        reader.GetOrdinal("Id")),

                    UserId =
                        reader["UserId"]?.ToString() ?? "",

                    FarmId =
                        Convert.ToInt32(
                            reader["FarmId"]),

                    CropName =
                        reader["CropName"]?.ToString() ?? "",

                    Variety =
                        reader["Variety"]?.ToString() ?? "",

                    Season =
                        reader["Season"]?.ToString() ?? "",

                    Area =
                        Convert.ToDouble(
                            reader["Area"]),

                    AreaUnit =
                        reader["AreaUnit"]?.ToString()
                        ?? "Acre",

                    SowingDate =
                        sowingDate,

                    Notes =
                        reader["Notes"]?.ToString() ?? "",

                    CreatedAt =
                        DateTime.Parse(
                            reader["CreatedAt"]?.ToString()
                            ?? DateTime.UtcNow.ToString("O"))
                });
            }

            return crops;
        }
        // =========================================================
        // GET SINGLE FARM CROP
        // =========================================================

        public FarmCrop? GetFarmCrop(
            int cropId,
            int farmId,
            string userId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmCrops
WHERE Id = @Id
AND FarmId = @FarmId
AND UserId = @UserId;
";

            AddParameter(command,
                "@Id",
                cropId);

            AddParameter(command,
                "@FarmId",
                farmId);

            AddParameter(command,
                "@UserId",
                userId);

            using var reader =
                command.ExecuteReader();

            if (!reader.Read())
            {
                return null;
            }

            DateTime? sowingDate = null;

            var sowingDateValue =
                reader["SowingDate"]?.ToString();

            if (!string.IsNullOrWhiteSpace(
                sowingDateValue))
            {
                if (DateTime.TryParse(
                    sowingDateValue,
                    out var parsedDate))
                {
                    sowingDate = parsedDate;
                }
            }

            return new FarmCrop
            {
                Id =
                    reader.GetInt32(
                        reader.GetOrdinal("Id")),

                UserId =
                    reader["UserId"]?.ToString() ?? "",

                FarmId =
                    Convert.ToInt32(
                        reader["FarmId"]),

                CropName =
                    reader["CropName"]?.ToString() ?? "",

                Variety =
                    reader["Variety"]?.ToString() ?? "",

                Season =
                    reader["Season"]?.ToString() ?? "",

                Area =
                    Convert.ToDouble(
                        reader["Area"]),

                AreaUnit =
                    reader["AreaUnit"]?.ToString()
                    ?? "Acre",

                SowingDate =
                    sowingDate,

                Notes =
                    reader["Notes"]?.ToString() ?? "",

                CreatedAt =
                    DateTime.Parse(
                        reader["CreatedAt"]?.ToString()
                        ?? DateTime.UtcNow.ToString("O"))
            };
        }


        // =========================================================
        // UPDATE FARM CROP
        // =========================================================

        public bool UpdateFarmCrop(
            FarmCrop crop)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
UPDATE FarmCrops
SET
    CropName = @CropName,
    Variety = @Variety,
    Season = @Season,
    Area = @Area,
    AreaUnit = @AreaUnit,
    SowingDate = @SowingDate,
    Notes = @Notes
WHERE Id = @Id
AND FarmId = @FarmId
AND UserId = @UserId;
";

            AddParameter(command,
                "@Id",
                crop.Id);

            AddParameter(command,
                "@FarmId",
                crop.FarmId);

            AddParameter(command,
                "@UserId",
                crop.UserId);

            AddParameter(command,
                "@CropName",
                crop.CropName);

            AddParameter(command,
                "@Variety",
                crop.Variety ?? "");

            AddParameter(command,
                "@Season",
                crop.Season ?? "");

            AddParameter(command,
                "@Area",
                crop.Area);

            AddParameter(command,
                "@AreaUnit",
                crop.AreaUnit ?? "Acre");

            AddParameter(command,
                "@SowingDate",
                crop.SowingDate?.ToString("O")
                ?? (object)DBNull.Value);

            AddParameter(command,
                "@Notes",
                crop.Notes ?? "");

            return command.ExecuteNonQuery() > 0;
        }


        // =========================================================
        // DELETE FARM CROP
        // =========================================================

        public bool DeleteFarmCrop(
            int cropId,
            int farmId,
            string userId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
DELETE FROM FarmCrops
WHERE Id = @Id
AND FarmId = @FarmId
AND UserId = @UserId;
";

            AddParameter(command,
                "@Id",
                cropId);

            AddParameter(command,
                "@FarmId",
                farmId);

            AddParameter(command,
                "@UserId",
                userId);

            return command.ExecuteNonQuery() > 0;
        }
        public FarmProfile? GetFarm(int id)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmProfiles
WHERE Id = @Id;
";

            AddParameter(command,
                "@Id",
                id);

            using var reader =
                command.ExecuteReader();

            if (!reader.Read())
            {
                return null;
            }

            return new FarmProfile
            {
                Id = reader.GetInt32(
                    reader.GetOrdinal("Id")),

                UserId =
                    reader["UserId"]?.ToString() ?? "",

                FarmerName =
                    reader["FarmerName"]?.ToString() ?? "",

                Location =
                    reader["Location"]?.ToString() ?? "",

                LandSize =
                    Convert.ToDouble(reader["LandSize"]),

                LandUnit =
                    reader["LandUnit"]?.ToString() ?? "",

                SoilType =
                    reader["SoilType"]?.ToString() ?? "",

                WaterSource =
                    reader["WaterSource"]?.ToString() ?? "",

                FarmingMethod =
                    reader["FarmingMethod"]?.ToString() ?? "",

                Crop =
                    reader["Crop"]?.ToString() ?? "",

                ExperienceLevel =
                    reader["ExperienceLevel"]?.ToString() ?? "",

                Budget =
                    Convert.ToDecimal(reader["Budget"]),

                CreatedAt =
                    DateTime.Parse(
                        reader["CreatedAt"]?.ToString()
                        ?? DateTime.UtcNow.ToString("O"))
            };
        }

        public FarmProfile? GetFarm(int id, string userId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmProfiles
WHERE Id = @Id
AND UserId = @UserId;
";

            AddParameter(command,
                "@Id",
                id);

            AddParameter(command,
                "@UserId",
                userId);

            using var reader =
                command.ExecuteReader();

            if (!reader.Read())
            {
                return null;
            }

            return new FarmProfile
            {
                Id = reader.GetInt32(
                    reader.GetOrdinal("Id")),

                UserId =
                    reader["UserId"]?.ToString() ?? "",

                FarmerName =
                    reader["FarmerName"]?.ToString() ?? "",

                Location =
                    reader["Location"]?.ToString() ?? "",

                LandSize =
                    Convert.ToDouble(reader["LandSize"]),

                LandUnit =
                    reader["LandUnit"]?.ToString() ?? "",

                SoilType =
                    reader["SoilType"]?.ToString() ?? "",

                WaterSource =
                    reader["WaterSource"]?.ToString() ?? "",

                FarmingMethod =
                    reader["FarmingMethod"]?.ToString() ?? "",

                Crop =
                    reader["Crop"]?.ToString() ?? "",

                ExperienceLevel =
                    reader["ExperienceLevel"]?.ToString() ?? "",

                Budget =
                    Convert.ToDecimal(reader["Budget"]),

                CreatedAt =
                    DateTime.Parse(
                        reader["CreatedAt"]?.ToString()
                        ?? DateTime.UtcNow.ToString("O"))
            };
        }

        public List<FarmProfile> GetFarmsByUserId(string userId)
        {
            var farms = new List<FarmProfile>();

            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmProfiles
WHERE UserId = @UserId
ORDER BY Id DESC;
";

            AddParameter(command,
                "@UserId",
                userId);

            using var reader =
                command.ExecuteReader();

            while (reader.Read())
            {
                farms.Add(new FarmProfile
                {
                    Id = reader.GetInt32(
                        reader.GetOrdinal("Id")),

                    UserId =
                        reader["UserId"]?.ToString() ?? "",

                    FarmerName =
                        reader["FarmerName"]?.ToString() ?? "",

                    Location =
                        reader["Location"]?.ToString() ?? "",

                    LandSize =
                        Convert.ToDouble(reader["LandSize"]),

                    LandUnit =
                        reader["LandUnit"]?.ToString() ?? "",

                    SoilType =
                        reader["SoilType"]?.ToString() ?? "",

                    WaterSource =
                        reader["WaterSource"]?.ToString() ?? "",

                    FarmingMethod =
                        reader["FarmingMethod"]?.ToString() ?? "",

                    Crop =
                        reader["Crop"]?.ToString() ?? "",

                    ExperienceLevel =
                        reader["ExperienceLevel"]?.ToString() ?? "",

                    Budget =
                        Convert.ToDecimal(reader["Budget"]),

                    CreatedAt =
                        DateTime.Parse(
                            reader["CreatedAt"]?.ToString()
                            ?? DateTime.UtcNow.ToString("O"))
                });
            }

            return farms;
        }


        public FarmProfile? GetLatestFarm()
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmProfiles
ORDER BY Id DESC
LIMIT 1;
";

            using var reader =
                command.ExecuteReader();

            if (!reader.Read())
            {
                return null;
            }

            return new FarmProfile
            {
                Id = reader.GetInt32(
                    reader.GetOrdinal("Id")),

                UserId =
                    reader["UserId"]?.ToString() ?? "",

                FarmerName =
                    reader["FarmerName"]?.ToString() ?? "",

                Location =
                    reader["Location"]?.ToString() ?? "",

                LandSize =
                    Convert.ToDouble(reader["LandSize"]),

                LandUnit =
                    reader["LandUnit"]?.ToString() ?? "",

                SoilType =
                    reader["SoilType"]?.ToString() ?? "",

                WaterSource =
                    reader["WaterSource"]?.ToString() ?? "",

                FarmingMethod =
                    reader["FarmingMethod"]?.ToString() ?? "",

                Crop =
                    reader["Crop"]?.ToString() ?? "",

                ExperienceLevel =
                    reader["ExperienceLevel"]?.ToString() ?? "",

                Budget =
                    Convert.ToDecimal(reader["Budget"]),

                CreatedAt =
                    DateTime.Parse(
                        reader["CreatedAt"]?.ToString()
                        ?? DateTime.UtcNow.ToString("O"))
            };
        }


        // =========================================================
        // FARM ACTIVITIES
        // =========================================================

        public void AddActivity(FarmActivity activity)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText = @"
INSERT INTO FarmActivities
(
    FarmProfileId,
    Title,
    Description,
    ActivityDate,
    IsCompleted,
    Category
)
VALUES
(
    @FarmProfileId,
    @Title,
    @Description,
    @ActivityDate,
    @IsCompleted,
    @Category
);
";

            AddParameter(command,
                "@FarmProfileId",
                activity.FarmProfileId);

            AddParameter(command,
                "@Title",
                activity.Title);

            AddParameter(command,
                "@Description",
                activity.Description);

            AddParameter(command,
                "@ActivityDate",
                activity.ActivityDate.ToString("O"));

            AddParameter(command,
                "@IsCompleted",
                activity.IsCompleted ? 1 : 0);

            AddParameter(command,
                "@Category",
                activity.Category);

            command.ExecuteNonQuery();
        }


        public List<FarmActivity> GetActivities(int farmId)
        {
            var activities =
                new List<FarmActivity>();

            using var connection =
                CreateConnection();

            connection.Open();

            using var command = connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM FarmActivities
WHERE FarmProfileId = @FarmProfileId
ORDER BY ActivityDate ASC;
";

            AddParameter(command,
                "@FarmProfileId",
                farmId);

            using var reader =
                command.ExecuteReader();

            while (reader.Read())
            {
                activities.Add(new FarmActivity
                {
                    Id = reader.GetInt32(
                        reader.GetOrdinal("Id")),

                    FarmProfileId =
                        reader.GetInt32(
                            reader.GetOrdinal("FarmProfileId")),

                    Title =
                        reader["Title"]?.ToString() ?? "",

                    Description =
                        reader["Description"]?.ToString() ?? "",

                    ActivityDate =
                        DateTime.Parse(
                            reader["ActivityDate"]?.ToString()
                            ?? DateTime.UtcNow.ToString("O")),

                    IsCompleted =
                        Convert.ToInt32(
                            reader["IsCompleted"]) == 1,

                    Category =
                        reader["Category"]?.ToString() ?? ""
                });
            }

            return activities;
        }

        // =========================================================
        // LEARNING LESSON COMPLETION
        // =========================================================

        public void MarkLessonCompleted(
            int farmId,
            int topicId,
            int lessonId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
INSERT INTO LearningLessonCompletions
(
    FarmProfileId,
    TopicId,
    LessonId,
    CompletedAt
)
VALUES
(
    @FarmProfileId,
    @TopicId,
    @LessonId,
    @CompletedAt
)
ON CONFLICT (FarmProfileId, TopicId, LessonId)
DO NOTHING;
";

            AddParameter(command,
                "@FarmProfileId",
                farmId);

            AddParameter(command,
                "@TopicId",
                topicId);

            AddParameter(command,
                "@LessonId",
                lessonId);

            AddParameter(command,
                "@CompletedAt",
                DateTime.UtcNow.ToString("O"));

            command.ExecuteNonQuery();
        }


        public List<int> GetCompletedLessonIds(
            int farmId,
            int topicId)
        {
            var completedLessonIds =
                new List<int>();

            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT LessonId
FROM LearningLessonCompletions
WHERE FarmProfileId = @FarmProfileId
AND TopicId = @TopicId
ORDER BY LessonId;
";

            AddParameter(command,
                "@FarmProfileId",
                farmId);

            AddParameter(command,
                "@TopicId",
                topicId);

            using var reader =
                command.ExecuteReader();

            while (reader.Read())
            {
                completedLessonIds.Add(
                    reader.GetInt32(
                        reader.GetOrdinal("LessonId")));
            }

            return completedLessonIds;
        }
        // =========================================================
        // UPDATE FARM ACTIVITY COMPLETION
        // =========================================================

        public bool UpdateActivityCompletion(
            int activityId,
            int farmId,
            bool isCompleted)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
UPDATE FarmActivities
SET IsCompleted = @IsCompleted
WHERE Id = @Id
AND FarmProfileId = @FarmProfileId;
";

            AddParameter(command,
                "@IsCompleted",
                isCompleted ? 1 : 0);

            AddParameter(command,
                "@Id",
                activityId);

            AddParameter(command,
                "@FarmProfileId",
                farmId);

            return command.ExecuteNonQuery() > 0;
        }

        // =========================================================
        // CROP OBSERVATIONS
        // =========================================================

        public int SaveCropObservation(
            int farmProfileId,
            string cropName,
            string imagePath,
            string observation,
            string aiResult)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
INSERT INTO CropObservations
(
    FarmProfileId,
    CropName,
    ImagePath,
    Observation,
    AiResult,
    CreatedAt
)
VALUES
(
    @FarmProfileId,
    @CropName,
    @ImagePath,
    @Observation,
    @AiResult,
    @CreatedAt
);

RETURNING Id;
";

            AddParameter(command,
                "@FarmProfileId",
                farmProfileId);

            AddParameter(command,
                "@CropName",
                cropName ?? "");

            AddParameter(command,
                "@ImagePath",
                imagePath ?? "");

            AddParameter(command,
                "@Observation",
                observation ?? "");

            AddParameter(command,
                "@AiResult",
                aiResult ?? "");

            AddParameter(command,
                "@CreatedAt",
                DateTime.UtcNow.ToString("O"));

            return Convert.ToInt32(
                command.ExecuteScalar());
        }


        public List<CropObservation> GetCropObservations(
            int farmProfileId,
            string cropName)
        {
            var observations =
                new List<CropObservation>();

            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM CropObservations
WHERE FarmProfileId = @FarmProfileId
AND LOWER(CropName) = LOWER(@CropName)
ORDER BY Id DESC;
";

            AddParameter(command,
                "@FarmProfileId",
                farmProfileId);

            AddParameter(command,
                "@CropName",
                cropName ?? "");

            using var reader =
                command.ExecuteReader();

            while (reader.Read())
            {
                observations.Add(new CropObservation
                {
                    Id = reader.GetInt32(
                        reader.GetOrdinal("Id")),

                    FarmProfileId =
                        reader.GetInt32(
                            reader.GetOrdinal("FarmProfileId")),

                    CropName =
                        reader["CropName"]?.ToString() ?? "",

                    ImagePath =
                        reader["ImagePath"]?.ToString() ?? "",

                    Observation =
                        reader["Observation"]?.ToString() ?? "",

                    AiResult =
                        reader["AiResult"]?.ToString() ?? "",

                    CreatedAt =
                        DateTime.Parse(
                            reader["CreatedAt"]?.ToString()
                            ?? DateTime.UtcNow.ToString("O"))
                });
            }

            return observations;
        }


        // =========================================================
        // SOIL ASSESSMENT
        // =========================================================

        public int SaveSoilAssessment(
            SoilAssessment assessment)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
INSERT INTO SoilAssessments
(
    FarmProfileId,
    SoilKnowledge,
    SoilTexture,
    SoilColour,
    Drainage,
    PreviousCrop,
    SoilTestStatus,
    Result,
    CreatedAt
)
VALUES
(
    @FarmProfileId,
    @SoilKnowledge,
    @SoilTexture,
    @SoilColour,
    @Drainage,
    @PreviousCrop,
    @SoilTestStatus,
    @Result,
    @CreatedAt
);

RETURNING Id;
";

            AddParameter(command,
                "@FarmProfileId",
                assessment.FarmProfileId);

            AddParameter(command,
                "@SoilKnowledge",
                assessment.SoilKnowledge);

            AddParameter(command,
                "@SoilTexture",
                assessment.SoilTexture);

            AddParameter(command,
                "@SoilColour",
                assessment.SoilColour);

            AddParameter(command,
                "@Drainage",
                assessment.Drainage);

            AddParameter(command,
                "@PreviousCrop",
                assessment.PreviousCrop);

            AddParameter(command,
                "@SoilTestStatus",
                assessment.SoilTestStatus);

            AddParameter(command,
                "@Result",
                assessment.Result);

            AddParameter(command,
                "@CreatedAt",
                assessment.CreatedAt.ToString("O"));

            return Convert.ToInt32(
                command.ExecuteScalar());
        }


        public SoilAssessment? GetSoilAssessment(
            int farmProfileId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM SoilAssessments
WHERE FarmProfileId = @FarmProfileId
ORDER BY Id DESC
LIMIT 1;
";

            AddParameter(command,
                "@FarmProfileId",
                farmProfileId);

            using var reader =
                command.ExecuteReader();

            if (!reader.Read())
            {
                return null;
            }

            return new SoilAssessment
            {
                Id = reader.GetInt32(
                    reader.GetOrdinal("Id")),

                FarmProfileId =
                    reader.GetInt32(
                        reader.GetOrdinal("FarmProfileId")),

                SoilKnowledge =
                    reader["SoilKnowledge"]?.ToString() ?? "",

                SoilTexture =
                    reader["SoilTexture"]?.ToString() ?? "",

                SoilColour =
                    reader["SoilColour"]?.ToString() ?? "",

                Drainage =
                    reader["Drainage"]?.ToString() ?? "",

                PreviousCrop =
                    reader["PreviousCrop"]?.ToString() ?? "",

                SoilTestStatus =
                    reader["SoilTestStatus"]?.ToString() ?? "",

                Result =
                    reader["Result"]?.ToString() ?? "",

                CreatedAt =
                    DateTime.Parse(
                        reader["CreatedAt"]?.ToString()
                        ?? DateTime.UtcNow.ToString("O"))
            };
        }


        // =========================================================
        // WATER ASSESSMENT
        // =========================================================

        public int SaveWaterAssessment(
            WaterAssessment assessment)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
INSERT INTO WaterAssessments
(
    FarmProfileId,
    WaterSource,
    WaterAvailability,
    IrrigationMethod,
    IrrigationFrequency,
    WaterQualityKnowledge,
    DrainageCondition,
    RecentWaterProblem,
    Result,
    CreatedAt
)
VALUES
(
    @FarmProfileId,
    @WaterSource,
    @WaterAvailability,
    @IrrigationMethod,
    @IrrigationFrequency,
    @WaterQualityKnowledge,
    @DrainageCondition,
    @RecentWaterProblem,
    @Result,
    @CreatedAt
);

RETURNING Id;
";

            AddParameter(command,
                "@FarmProfileId",
                assessment.FarmProfileId);

            AddParameter(command,
                "@WaterSource",
                assessment.WaterSource ?? "");

            AddParameter(command,
                "@WaterAvailability",
                assessment.WaterAvailability ?? "");

            AddParameter(command,
                "@IrrigationMethod",
                assessment.IrrigationMethod ?? "");

            AddParameter(command,
                "@IrrigationFrequency",
                assessment.IrrigationFrequency ?? "");

            AddParameter(command,
                "@WaterQualityKnowledge",
                assessment.WaterQualityKnowledge ?? "");

            AddParameter(command,
                "@DrainageCondition",
                assessment.DrainageCondition ?? "");

            AddParameter(command,
                "@RecentWaterProblem",
                assessment.RecentWaterProblem ?? "");

            AddParameter(command,
                "@Result",
                assessment.Result ?? "");

            AddParameter(command,
                "@CreatedAt",
                assessment.CreatedAt.ToString("O"));

            return Convert.ToInt32(
                command.ExecuteScalar());
        }


        public WaterAssessment? GetWaterAssessment(
            int farmProfileId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var command =
                connection.CreateCommand();

            command.CommandText = @"
SELECT *
FROM WaterAssessments
WHERE FarmProfileId = @FarmProfileId
ORDER BY Id DESC
LIMIT 1;
";

            AddParameter(command,
                "@FarmProfileId",
                farmProfileId);

            using var reader =
                command.ExecuteReader();

            if (!reader.Read())
            {
                return null;
            }

            return new WaterAssessment
            {
                Id = reader.GetInt32(
                    reader.GetOrdinal("Id")),

                FarmProfileId =
                    reader.GetInt32(
                        reader.GetOrdinal("FarmProfileId")),

                WaterSource =
                    reader["WaterSource"]?.ToString() ?? "",

                WaterAvailability =
                    reader["WaterAvailability"]?.ToString() ?? "",

                IrrigationMethod =
                    reader["IrrigationMethod"]?.ToString() ?? "",

                IrrigationFrequency =
                    reader["IrrigationFrequency"]?.ToString() ?? "",

                WaterQualityKnowledge =
                    reader["WaterQualityKnowledge"]?.ToString() ?? "",

                DrainageCondition =
                    reader["DrainageCondition"]?.ToString() ?? "",

                RecentWaterProblem =
                    reader["RecentWaterProblem"]?.ToString() ?? "",

                Result =
                    reader["Result"]?.ToString() ?? "",

                CreatedAt =
                    DateTime.Parse(
                        reader["CreatedAt"]?.ToString()
                        ?? DateTime.UtcNow.ToString("O"))
            };
        }

        // =========================================================
        // DELETE FARM
        // Deletes the farm and all data belonging to it.
        // UserId check prevents deleting another user's farm.
        // =========================================================

        public bool DeleteFarm(
            int farmId,
            string userId)
        {
            using var connection =
                CreateConnection();

            connection.Open();

            using var transaction =
                connection.BeginTransaction();

            try
            {
                // -------------------------------------------------
                // FIRST VERIFY THAT THIS FARM BELONGS TO THE USER
                // -------------------------------------------------

                using (var checkCommand =
                    connection.CreateCommand())
                {
                    checkCommand.Transaction = transaction;

                    checkCommand.CommandText = @"
SELECT COUNT(*)
FROM FarmProfiles
WHERE Id = @FarmId
AND UserId = @UserId;
";

                    AddParameter(checkCommand,
                        "@FarmId",
                        farmId);

                    AddParameter(checkCommand,
                        "@UserId",
                        userId);

                    var exists =
                        Convert.ToInt32(
                            checkCommand.ExecuteScalar());

                    if (exists == 0)
                    {
                        transaction.Rollback();

                        return false;
                    }
                }


                // -------------------------------------------------
                // DELETE FARM CROPS
                // -------------------------------------------------

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM FarmCrops
WHERE FarmId = @FarmId
AND UserId = @UserId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    AddParameter(command,
                        "@UserId",
                        userId);

                    command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // DELETE FARM ACTIVITIES
                // -------------------------------------------------

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM FarmActivities
WHERE FarmProfileId = @FarmId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // DELETE LEARNING PROGRESS
                // -------------------------------------------------

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM LearningLessonCompletions
WHERE FarmProfileId = @FarmId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // DELETE CROP OBSERVATIONS
                // -------------------------------------------------

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM CropObservations
WHERE FarmProfileId = @FarmId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // DELETE SOIL ASSESSMENTS
                // -------------------------------------------------

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM SoilAssessments
WHERE FarmProfileId = @FarmId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // DELETE WATER ASSESSMENTS
                // -------------------------------------------------

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM WaterAssessments
WHERE FarmProfileId = @FarmId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // FINALLY DELETE THE FARM
                // -------------------------------------------------

                int deletedRows;

                using (var command =
                    connection.CreateCommand())
                {
                    command.Transaction = transaction;

                    command.CommandText = @"
DELETE FROM FarmProfiles
WHERE Id = @FarmId
AND UserId = @UserId;
";

                    AddParameter(command,
                        "@FarmId",
                        farmId);

                    AddParameter(command,
                        "@UserId",
                        userId);

                    deletedRows =
                        command.ExecuteNonQuery();
                }


                // -------------------------------------------------
                // COMMIT
                // -------------------------------------------------

                if (deletedRows > 0)
                {
                    transaction.Commit();

                    return true;
                }


                transaction.Rollback();

                return false;
            }
            catch
            {
                transaction.Rollback();

                throw;
            }
        }
    }
}